"""
Export Endpoint — FR-05: PDF bundle generation for notices and petitions
"""
from fastapi import APIRouter, Query
from fastapi.responses import StreamingResponse
import io

router = APIRouter()


def generate_simple_pdf(content: str) -> bytes:
    """Generate a minimal PDF as plain text (placeholder for reportlab integration)."""
    pdf_header = b"%PDF-1.4\n"
    content_bytes = content.encode("utf-8")
    return pdf_header + content_bytes


@router.get("/notice")
async def export_notice(session_id: str = Query(..., description="Session ID")):
    """Export Tier 1 Legal Notice as PDF."""
    content = f"""LEXIS COUNSEL — LEGAL NOTICE
Session: {session_id}
Generated by Lexis Counsel / CivicLegal-AI

[Full notice content would be rendered here via reportlab]
"""
    pdf_bytes = generate_simple_pdf(content)
    return StreamingResponse(
        io.BytesIO(pdf_bytes),
        media_type="application/pdf",
        headers={"Content-Disposition": f"attachment; filename=Legal_Notice_{session_id}.pdf"},
    )


@router.get("/pdf")
async def export_pdf_bundle(session_id: str = Query(..., description="Session ID")):
    """Export full e-Daakhil petition bundle as PDF."""
    content = f"""LEXIS COUNSEL — COURT PETITION BUNDLE
Session: {session_id}
Forum: District Consumer Disputes Redressal Commission
Generated: CivicLegal-AI v1.1.0

CONTENTS:
1. Index of Documents & Court Fee
2. List of Dates & Synopsis
3. Memo of Parties
4. Statement of Facts & Grounds
5. Prayer Clause
6. Verification Affidavit

[Full petition bundle would be compiled via reportlab]
"""
    pdf_bytes = generate_simple_pdf(content)
    return StreamingResponse(
        io.BytesIO(pdf_bytes),
        media_type="application/pdf",
        headers={"Content-Disposition": f"attachment; filename=Petition_Bundle_{session_id}.pdf"},
    )
